{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4bd10eb3",
   "metadata": {},
   "outputs": [],
   "source": [
    "#include <Arduino.h>\n",
    "\n",
    "// --- Pin Definitions ---\n",
    "// Level Sensors (Digital / Float Switches)\n",
    "const int PIN_COLLECTE_BAS  = 34; // Low level threshold for collection tank (5000L)[cite: 1]\n",
    "const int PIN_COLLECTE_HAUT = 35; // High level threshold for collection tank (5000L)[cite: 1]\n",
    "const int PIN_DISTRIB_HAUT  = 32; // High level threshold for distribution tank (6000L)[cite: 1]\n",
    "\n",
    "// Sensors & Measurements\n",
    "const int PIN_SONDE_EC      = 33; // Conductivity sensor (Analog Input)[cite: 1]\n",
    "const int PIN_BATT_VOLT     = 36; // Battery voltage monitoring (Voltage divider)[cite: 1]\n",
    "\n",
    "// Actuators (via relay module - active high/low depending on hardware configuration)\n",
    "const int PIN_RELAY_EV1     = 23; // EV1: RO reject inflow to collection tank[cite: 1]\n",
    "const int PIN_RELAY_RECYC   = 22; // EV_recyclage: Upstream recycling to RO feed[cite: 1]\n",
    "const int PIN_RELAY_EV2     = 21; // EV2: Distribution for external usages[cite: 1]\n",
    "\n",
    "// --- Configuration Thresholds ---\n",
    "const float SEUIL_CONDUCTIVITE_MAX = 2.5; // in mS/cm (Example limit to be calibrated)\n",
    "const float TENSION_CRITIQUE_BATT  = 10.5; // in Volts (Critical safety limit for 12V battery)[cite: 1]\n",
    "\n",
    "// --- System States (Grafcet) ---\n",
    "enum SystemState {\n",
    "  STATE_IDLE = 0,\n",
    "  STATE_COLLECT,\n",
    "  STATE_ARBITRATION,\n",
    "  STATE_UPSTREAM_RECYCLING,\n",
    "  STATE_DISTRIBUTION,\n",
    "  STATE_SAFETY_LOCKDOWN\n",
    "};\n",
    "\n",
    "SystemState currentState = STATE_IDLE;\n",
    "\n",
    "void setup() {\n",
    "  Serial.begin(115200);\n",
    "\n",
    "  // Configure Inputs\n",
    "  pinMode(PIN_COLLECTE_BAS, INPUT_PULLUP);\n",
    "  pinMode(PIN_COLLECTE_HAUT, INPUT_PULLUP);\n",
    "  pinMode(PIN_DISTRIB_HAUT, INPUT_PULLUP);\n",
    "  pinMode(PIN_SONDE_EC, INPUT);\n",
    "  pinMode(PIN_BATT_VOLT, INPUT);\n",
    "\n",
    "  // Configure Outputs (Relays)\n",
    "  pinMode(PIN_RELAY_EV1, OUTPUT);\n",
    "  pinMode(PIN_RELAY_RECYC, OUTPUT);\n",
    "  pinMode(PIN_RELAY_EV2, OUTPUT);\n",
    "\n",
    "  // Initial State: Close all valves (RELAIS OFF)\n",
    "  digitalWrite(PIN_RELAY_EV1, LOW);\n",
    "  digitalWrite(PIN_RELAY_RECYC, LOW);\n",
    "  digitalWrite(PIN_RELAY_EV2, LOW);\n",
    "\n",
    "  Serial.println(\"RO Reject Valorization System Initialized.\");\n",
    "}\n",
    "\n",
    "void loop() {\n",
    "  // 1. Continuous Safety Monitoring\n",
    "  int rawBatt = analogRead(PIN_BATT_VOLT);\n",
    "  float batteryVoltage = (rawBatt / 4095.0) * 3.3 * 4.0; // Estimated factor 4 for voltage divider\n",
    "\n",
    "  if (batteryVoltage < TENSION_CRITIQUE_BATT && batteryVoltage > 1.0) {\n",
    "    currentState = STATE_SAFETY_LOCKDOWN;\n",
    "  }\n",
    "\n",
    "  // 2. State Machine (Grafcet logic)[cite: 1]\n",
    "  switch (currentState) {\n",
    "    \n",
    "    case STATE_IDLE:\n",
    "      Serial.println(\"[STATE 0] - Idle / Waiting[cite: 1]\");\n",
    "      digitalWrite(PIN_RELAY_EV1, LOW);\n",
    "      digitalWrite(PIN_RELAY_RECYC, LOW);\n",
    "      digitalWrite(PIN_RELAY_EV2, LOW);\n",
    "\n",
    "      // Transition: If collection tank level drops below low threshold[cite: 1]\n",
    "      if (digitalRead(PIN_COLLECTE_BAS) == LOW) { \n",
    "        currentState = STATE_COLLECT;\n",
    "      }\n",
    "      break;\n",
    "\n",
    "    case STATE_COLLECT:\n",
    "      Serial.println(\"[STATE 1] - Collecting reject water (Opening EV1)[cite: 1]\");\n",
    "      digitalWrite(PIN_RELAY_EV1, HIGH); // Open inflow to collection\n",
    "\n",
    "      // Transition: If collection tank reaches maximum capacity (5000L)[cite: 1]\n",
    "      if (digitalRead(PIN_COLLECTE_HAUT) == HIGH) {\n",
    "        digitalWrite(PIN_RELAY_EV1, LOW);\n",
    "        currentState = STATE_ARBITRATION;\n",
    "      }\n",
    "      break;\n",
    "\n",
    "    case STATE_ARBITRATION:\n",
    "      Serial.println(\"[STATE 2] - Arbitration (Evaluating conductivity)[cite: 1]\");\n",
    "      {\n",
    "        int rawEC = analogRead(PIN_SONDE_EC);\n",
    "        float conductivity = (rawEC / 4095.0) * 20.0; // 0-20 mS/cm scale[cite: 1]\n",
    "\n",
    "        bool distributionTankFull = (digitalRead(PIN_DISTRIB_HAUT) == HIGH);\n",
    "\n",
    "        // Transition to upstream recycling or general distribution[cite: 1]\n",
    "        if (conductivity < SEUIL_CONDUCTIVITE_MAX && !distributionTankFull) {\n",
    "          currentState = STATE_UPSTREAM_RECYCLING;\n",
    "        } else {\n",
    "          currentState = STATE_DISTRIBUTION;\n",
    "        }\n",
    "      }\n",
    "      break;\n",
    "\n",
    "    case STATE_UPSTREAM_RECYCLING:\n",
    "      Serial.println(\"[STATE 3] - Upstream recycling towards RO feed[cite: 1]\");\n",
    "      digitalWrite(PIN_RELAY_RECYC, HIGH); // Open recycling valve\n",
    "\n",
    "      // Simulation of condition window (replace with actual RO demand trigger)\n",
    "      delay(2000); \n",
    "      digitalWrite(PIN_RELAY_RECYC, LOW);\n",
    "      currentState = STATE_IDLE;\n",
    "      break;\n",
    "\n",
    "    case STATE_DISTRIBUTION:\n",
    "      Serial.println(\"[STATE 4] - Distributing to external water utilities (EV2)[cite: 1]\");\n",
    "      digitalWrite(PIN_RELAY_EV2, HIGH); // Open distribution valve\n",
    "\n",
    "      // Simulation of distribution cycle completion\n",
    "      delay(3000); \n",
    "      digitalWrite(PIN_RELAY_EV2, LOW);\n",
    "      currentState = STATE_IDLE;\n",
    "      break;\n",
    "\n",
    "    case STATE_SAFETY_LOCKDOWN:\n",
    "      Serial.println(\"[ALERT] - Critical battery voltage detected! Fail-safe lockdown activated[cite: 1].\");\n",
    "      // Fail-Safe Mode: Shut down all valves immediately[cite: 1]\n",
    "      digitalWrite(PIN_RELAY_EV1, LOW);\n",
    "      digitalWrite(PIN_RELAY_RECYC, LOW);\n",
    "      digitalWrite(PIN_RELAY_EV2, LOW);\n",
    "      \n",
    "      // Halt execution until system is reset or recharged\n",
    "      while (true) {\n",
    "        delay(1000);\n",
    "      }\n",
    "      break;\n",
    "  }\n",
    "\n",
    "  delay(1000); // 1-second loop execution delay\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
